web_blog/blog_board/urls.py
from django.urls import path
from blog_board.views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('<int:blog_id>/', detail_blog, name='blog_view'),
    path('create/', CreateBlogView.as_view(), name='blog_creation'),
    path('create/from_csv/', CreateBlogFromCSV.as_view(), name='blog_csv_creation'),
    path('<int:blog_id>/add_com/', CreateCommentView.as_view(), name='comment_creation'),
    path('<int:blog_id>/edit_com/<int:comm_id>/', EditCommentView.as_view(), name='edit_comment'),
]+ static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

#конструкция +static... помогает корректно обрабатывать ссылки на файлы

web_blog/web_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('blog_board.urls')),
    path('', include('user_auth.urls')),
]

web_blog/blog_board/models.py
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.contrib.auth.models import User


class Blogs(models.Model):

    ACTIVITY_CHOISES = [
        (0, _('On cheak')), #отобразить на странице профиля статус постов
        (1, _('Approved')),
        (2, _('Not approved (leave your comment)')) #рассмотреть возможность указания причины от модератора в  личном профиле
    ]

    title = models.CharField(max_length=15, verbose_name=_('Title'))
    text  = models.CharField(max_length=1000, verbose_name=_('Content'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('Created_at'))
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,
                            related_name='blog_author', verbose_name=_('User'))
    is_active = models.IntegerField(default=0, verbose_name=_('Approve by moderator'),
                                    choices=ACTIVITY_CHOISES)

    def __str__(self):
        if len(self.text) > 100:
            return f"{self.text[:100]}..." #ограничение на отображение 100 символов при вызове объекта
        return self.text

    class Meta:
        db_table = 'Блоги'          #название таблицы
        ordering = ['-created_at']   #сортировка по умолчанию по дате создания
        permissions = (
            ('can_activate', 'Can activate posts'),
        )
        verbose_name_plural = _('blogs') # для интернационализации модели
        verbose_name = _('blog')


class ModerComment(models.Model): # отработать удобную логику, сейчас совсем не удобно

    content = models.CharField(max_length=200, verbose_name=_('Comment from moderator'))
    post = models.OneToOneField(Blogs, on_delete=models.CASCADE, null=True,
                                related_name='post', verbose_name=_('Not approved post'))

    def __str__(self):
        return self.content

    class Meta:
        db_table = 'Комментарий модератора'
        verbose_name_plural = _('moder_comments') # для интернационализации модели
        verbose_name = _('moder_comment')
    

class BlogPhotos(models.Model):

    file = models.ImageField(upload_to='blog_photos/')

    post = models.ForeignKey(Blogs, on_delete=models.CASCADE, null=True,
                            verbose_name=_('Post'), related_name='post1')

    class Meta:
        db_table = 'Фото публикаций'
        verbose_name_plural = _('blog_photos') # для интернационализации модели
        verbose_name = _('blog_photo')

class Comments(models.Model):

    DELETE_CHOISES = [
        (True, 'Удалено модератором'),
        (False, '')
    ]

    content = models.CharField(max_length=500, verbose_name=_('Comment'))
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,
                            related_name='comment_author', verbose_name=_('User'))
    blog = models.ForeignKey(Blogs, on_delete=models.CASCADE, null=True,
                            related_name='blog', verbose_name=_('Blog'))
    ban_status = models.BooleanField(default=False, verbose_name=_('Status'),
                                choices=DELETE_CHOISES)

    class Meta:
        db_table = 'Комментарии'
        ordering = ['-created_at']

        permissions = (
            ('can_ban', 'Can ban comments'),
        )
        verbose_name_plural = _('comments') # для интернационализации модели
        verbose_name = _('comment')

web_blog/blog_board/forms.py
from django import forms
from blog_board.models import Comments
from django.core.exceptions import ValidationError
import csv


class BlogForm(forms.Form):
    title = forms.CharField(label='Заголовок', max_length=15, required=True)
    text = forms.CharField(label='Содержание', max_length=1000, widget=forms.Textarea, required=True)
    images = forms.ImageField(label='Фото', widget=forms.ClearableFileInput(attrs={'multiple':True}), required=False)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('content',)

#for for csv loading
class CSVForm(forms.Form):
    file = forms.FileField(label='CSV файл')

    def clean_file(self): #название должно быть clean_*название поля*
        file = self.cleaned_data['file']
        f = file.read().decode('utf-8').strip().split('\n') #читаем csv файл, убираем лишнии пустые строки, разделяем по строкам
        csv_file = csv.reader(f, delimiter=';') #разбираем построчно по разделителю ';', т.к он в csv файле
        for raw in csv_file:
            print(raw)
            if not (raw[0] == 'Title' and raw[1] == 'Text'):
                raise ValidationError(f"Неправильная структура переданного файла:"
                                        "первый столбец должен иметь название 'Title',"
                                        " второй столбец дожнен иметь название 'Text'")
            break
       
        return csv_file #вернет в cleadned_data['file'] csv_file

web_blog/blog_board/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView
from blog_board.models import Blogs, Comments, BlogPhotos
from blog_board.forms import BlogForm, CommentForm, CSVForm

class BlogListView(ListView):
    model = Blogs
    context_object_name = 'blog_list'
    template_name = 'blog_board/listblog_view.html'


def detail_blog(request, blog_id):
    
    blog = Blogs.objects.get(id=blog_id)

    return render(request, 'blog_board/blog_view.html', context={'blog':blog})


class CreateBlogView(View):
    
    def get(self, request):

        form = BlogForm

        return render(request, 'blog_board/create_blog.html', context={'form':form})

    def post(self, request):
        form = BlogForm(request.POST, request.FILES)

        if form.is_valid():
            #form.cleaned_data['user'] = request.user
            blog = Blogs.objects.create(**{
                'title':form.cleaned_data['title'],
                'text':form.cleaned_data['text'],
                'user':request.user
            })
            files = request.FILES.getlist('images')
            if files:
                for f in files:
                    BlogPhotos.objects.create(**{
                        'file':f,
                        'post':blog
                    })
            return HttpResponseRedirect('../')
        return render(request, 'blog_board/create_blog.html', context={'form':form})


class CreateBlogFromCSV(View):
    
    def get(self, request):

        form = CSVForm

        return render(request, 'blog_board/csv_loading.html', context={'form':form})

    def post(self, request):
        
        form = CSVForm(request.POST, request.FILES)

        if form.is_valid():
            csv_file = form.cleaned_data['file']
            for raw in csv_file:
                    title = raw[0]
                    text = raw[1]
                    new_post = Blogs.objects.create(**{
                        'title':title,
                        'text':text,
                        'user':request.user
                    })
                    BlogPhotos.objects.create(**{   #создаем объект в этой БД, чтобы обеспечить работу функции blog_view 
                        'post':new_post
                    })
            return HttpResponseRedirect('../../')

        return render(request, 'blog_board/csv_loading.html', context={'form':form})

class CreateCommentView(View):
    
    def get(self, request, blog_id):

        form = CommentForm

        return render(request, 'blog_board/create_comment.html', context={'form':form})

    def post(self, request, blog_id):

        form = CommentForm(request.POST)

        if form.is_valid():
            form.cleaned_data['user'] = request.user
            form.cleaned_data['blog_id'] = blog_id
            Comments.objects.create(**form.cleaned_data)
            return HttpResponseRedirect('../')

        return render(request, 'blog_board/create_comment.html', context={'form':form})


class EditCommentView(View):

    def get(self, request, blog_id, comm_id):

        comment = Comments.objects.get(id=comm_id)
        form = CommentForm(instance=comment)

        return render(request, 'blog_board/edit_comment.html', context={'form':form})

    def post(self, request, blog_id, comm_id):#blog_id необходимо указать для работы ссылки редиректа

        form = CommentForm(request.POST)

        if form.is_valid():
            Comments.objects.filter(id=comm_id).update(content=form.cleaned_data['content'])
            return HttpResponseRedirect('../../') #редирект обратно к новости

        return render(request, 'blog_board/edit_comment.html', context={'form':form})

web_blog/blog_board/templates/blog_board/blog_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ blog.title }}</title>
</head>
<body>
    <h1> {{ blog.title }} </h1>
    <p> {{ blog.text }} </p>
    {% for image in blog.post1.all %}
        <img src="{{ image.file.url }}" alt="Фото {{ image.id }}" width="150">
    {% endfor %}
    <p> Автор: {{ blog.user.username }} </p>
    <p> Дата создания: {{ blog.created_at }} </p>
    {% if not blog.is_active == 2 %}
        {% if not blog.blog.all.count == 0 %}
            <h3>Комментарии ({{ blog.blog.all.count }}):</h3>
            {% for comment in blog.blog.all %}
                <h4> {{ comment.user }} | {{ comment.created_at }} </h4>
                {% if comment.ban_status %}
                    <p><i>Удален модератором </i></p>
                {% else %}
                    <p> {{ comment.content }} </p>
                {% endif %}
                {% if request.user == comment.user %}
                    <a href="/blogs/{{ blog.id }}/edit_com/{{ comment.id }}/">ред.</a> 
                {% endif %}
            {% endfor %}
        {% else %}
            <h2>Комментариев нет</h2>
        {% endif %}
        {% if blog.is_active == 1 %}
            {% if perms.blog_board.add_comments %}
                <p><button><a href="/blogs/{{ blog.id }}/add_com/">Добавить комментарий</a></button></p>
            {% endif %}
        {% endif %}
    {% else %}
        {% if blog.post %}
            <h5>Комментарий модератора:</h5>
            {{ blog.post }}
        {% else %}
            <h5>Модератор скоро оставит комментарий</h5>
        {% endif %}
    {% endif %}

</body>
</html>

web_blog/blog_board/templates/blog_board/create_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Создание записи</title>
</head>
<body>
    <button><a href="from_csv/">Создать несколько записей из файла CSV</a></button>
    <form method="post" action="#" enctype="multipart/form-data">
        {% if not request.user.is_authenticated %}
            <h4>Создавать записи могут только авторизированные пользователи</h4>
        {% else %}
            {% csrf_token %}
            {{ form.as_p }}
        {% endif %}
        <button type="submit">Опубликовать</button>
    </form>
</body>
</html>

web_blog/blog_board/templates/blog_board/create_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Напишите комментарий</title>
</head>
<body>
    <form method="post" action="">
        {% if not request.user.is_authenticated %}
            <h4>Комментировать записи могут только авторизированные пользователи</h4>
        {% else %}
            {% csrf_token %}
            {{ form.as_p }}
        {% endif %}
        <button type="submit">Опубликовать</button>
    </form>
</body>
</html>

web_blog/blog_board/templates/blog_board/csv_loading.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Создание публикации</title>
</head>
<body>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Загрузить</button>
    </form>
</body>
</html>

web_blog/blog_board/templates/blog_board/edit_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Редактирование комментариев</title>
</head>
<body>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Опубликовать</button>
    </form>
</body>
</html>

web_blog/blog_board/templates/blog_board/listblog_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Записи</title>
</head>
<body>
    {% if blog_list %}
        <h1>Все записи</h1>
        {% if request.user.is_authenticated %}
            <p><a href="/profile/">Мой профиль</a></p>
            <button><a href="create/">Создать запись</a></button>
        {% endif %}
        {% for blog in blog_list %}
            {% if blog.is_active == 1 %}
                <h3><a href="{{ blog.id }}/"> {{ blog.title }} </a></h3>
                <p>Автор: {{ blog.user.username }}</p>
                <p>{{ blog }}</p> <! ограничение на 100 символов реализовано в models, def str!>
            {% endif %}
        {% endfor %}
    {% else %}
        <h2>Записей еще нет</h2>
    {% endif %}
</body>
</html>